travis:
  secure:
    BINSTAR_TOKEN: sLnIWqy5VWtOimc/YzzmI6At1Oihwt6BJ+ADN6eutozU31yFVMiQ3UaMXWZd9U+V2xKsn4eTnlT9w6ApKVnZNAyI/8QaJAf5lc+qzbs6b76bt8295DT7WYcUNlqpCqpeHdPo49r5TaK2DPWRRvAF7MO9QannwOt8ft9Ii+eeCJWhkRDtDgY5i+lIgBLlKpgsluNRJj2eYbSui2RTaMqnY39UzQM7AoBP+xewt1h54x0D9ENX+mgJ+Pk7ScMnfM1KrPQvXXPa1pNrgCSY0nUo82T32Z8SqNtqrD5Bwj2hRIMJbfauC/J2JhJfSNiYKqHQ+ec7aGGVS71EhPvLMiIql9yiU4guqeJ8lQ4w6HI7pbkkZ+ATII7LYM77PQMt0O+BsYZos7rCKpN0ozZuQl90dqy9czb0utkIYQlYhdjJTy3PQwcIOamvm8yf8Yc09kDJTX86KJxW80lFl7r92OBpq7RcGl6DhegxaCG4KjL5wrtFmWJN3b8Y650OeyrF+ln8KbJB+7BmiJsE2u/nTvNtr4DD7atT2x304dyiJpECcZWhy6VNJYAnQ631Kli/iDaDPcFw+Nikuis14p8aLz6GU4RJQBBNReMQawnBC5B1O/eZ8q0xyHfsPdROj08yxkjXvMs8EvALLaKNaJV0iVXuCzCsr/Tl+EaGV+mPPNYPF7g=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
