travis:
  secure:
    BINSTAR_TOKEN: fuT+n5S5T2L28QA0zXo1PWmUpEhPHpm/iSCOl+vR9KPlK6j+uKWw5rNTQ2TUDo5H6lOXEeBk6TMdmsvt/qKyv/pUhGrxMiICDHFGi2a9x1MW9XWWnBxQe45sAm+0De1hTCNwvge4nURUZc58ij6X4Q2FVFhLl8TyrgKMhpTjpXqKztJCVWKyGBmIQMw2FZRCQBFERxT3UmMEzo8q/0I6A3VDdXTQkXTu75b3ZY10yPSRFUqU/BGijaD2Xm7wLwfEsQfzWpbtKRicemctGgTZQmPiZGzXDFZGEDOEWfDvMfDt2EYHiXmVBmrF9nhJVY2NvacLoEXtVu+n55wGcAEM+9McRKSP12ubSCkeSm58VQKOvOdzJco7j1nfIwGnNyJncGA0TXw462WcQTI0zaCE272ifIeEzYebW9Q6HQ8XluBxDTSMMNjoxwQQsD59jvhBK85V2wZ3gofouCl64yhH0dwvhxgMxhxXX5hBKUWYPrvd4eGrU7DOTlPaU8qDzonqEa2k1u5MBDzG2TwolI9et4i3Wkt1Pj63m0+h6/wVq+7Jotl6I2NA+CpFkeytc7dZtSkPMY2WzsQHEU88e8ol2H/FfUc7qkw6veguwdXdBf/PEuvEiCV+Fqt30i0ACyFUiEeZNKyR0oD/IvOkZMhEntrrGzeOWfpWfprBQ+5hLz4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
